class_name CharacterSprites
extends RefCounted
## LimeZu's layered character sheets (D-019): which layers a person wears, and
## which part of a sheet shows a given facing and frame.
##
## The art is not in the repository (its licence forbids redistribution);
## `tools/import_limezu.py` builds it locally with a manifest. When the
## manifest is missing, `available()` is false and CharacterFigure keeps
## drawing the code-painted person, so the game runs either way.
##
## A look is chosen, never stored: the id picks the styles, and the person's
## palette (authored or generated by NpcLook) picks the closest colour variant.
## The same person therefore looks the same in every session and save.

const DIR := "res://art/vendor/limezu/characters/"
const MANIFEST := DIR + "manifest.json"
const FRAME := Vector2i(32, 64)
const FRAMES_PER_FACING := 6
const ROW_STAND := 0
const ROW_WALK := 2
## Column order of the four facings in every sheet.
const FACINGS: Array[Vector2i] = [Vector2i.RIGHT, Vector2i.UP, Vector2i.LEFT, Vector2i.DOWN]
## Drawing order, bottom to top.
const LAYERS: Array[String] = ["bodies", "eyes", "outfits", "hairstyles"]

static var _manifest: Dictionary = {}
static var _loaded := false
static var _textures: Dictionary = {}   # file -> Texture2D


static func available() -> bool:
	return not manifest().is_empty()


static func manifest() -> Dictionary:
	if not _loaded:
		_loaded = true
		_manifest = {}
		if FileAccess.file_exists(MANIFEST):
			_manifest = SafeJson.parse_dict(FileAccess.get_file_as_string(MANIFEST))
	return _manifest


## Replaces the manifest; tests use it to run without the art. Pass {} and
## call `reset()` to go back to reading the file.
static func use_manifest(data: Dictionary) -> void:
	_manifest = data
	_loaded = true
	_textures.clear()


static func reset() -> void:
	_manifest = {}
	_loaded = false
	_textures.clear()


## The layer files a person wears, keyed by layer. Empty when there is no art.
## `chosen` names a style per layer ("outfits" -> "12") where someone picked
## one rather than having it rolled from their id — the player, from the
## creation screen (D-033). A chosen style the art does not have is ignored.
static func look_for(person_id: String, palette: Dictionary, chosen: Dictionary = {}) -> Dictionary:
	var data := manifest()
	if data.is_empty():
		return {}
	var look := {}
	var bodies: Array = data.get("bodies", [])
	var eyes: Array = data.get("eyes", [])
	if bodies.is_empty():
		return {}
	look["bodies"] = _closest(bodies, _palette_colour(palette, "skin"))
	if not eyes.is_empty():
		var chosen_eyes: Dictionary = eyes[posmod(_roll(person_id, "eyes"), eyes.size())]
		look["eyes"] = str(chosen_eyes["file"])
	var outfit := _styled(data.get("outfits", []), _roll(person_id, "outfits"),
		_palette_colour(palette, "shirt"), str(chosen.get("outfits", "")))
	if outfit != "":
		look["outfits"] = outfit
	var hair := _styled(data.get("hairstyles", []), _roll(person_id, "hairstyles"),
		_palette_colour(palette, "hair"), str(chosen.get("hairstyles", "")))
	if hair != "":
		look["hairstyles"] = hair
	return look


## The styles a layer offers, sorted ("01", "02", ...). Empty without the art.
static func styles(layer: String) -> Array[String]:
	var out: Array[String] = []
	for entry: Dictionary in manifest().get(layer, []):
		var style := str(entry.get("style", ""))
		if style != "" and not out.has(style):
			out.append(style)
	out.sort()
	return out


## The textures of a look, bottom layer first. Missing files are skipped.
static func textures_for(look: Dictionary) -> Array[Texture2D]:
	var out: Array[Texture2D] = []
	for layer in LAYERS:
		if not look.has(layer):
			continue
		var file := str(look[layer])
		if not _textures.has(file):
			var path := DIR + file
			_textures[file] = load(path) if ResourceLoader.exists(path) else null
		var texture: Texture2D = _textures[file]
		if texture != null:
			out.append(texture)
	return out


## The part of a sheet that shows this facing, standing or at a walk frame.
static func frame_rect(facing: Vector2i, moving: bool, frame: int) -> Rect2i:
	var side := maxi(FACINGS.find(facing), 0)
	if not moving:   # the standing row holds one frame per facing
		return Rect2i(Vector2i(side * FRAME.x, ROW_STAND * FRAME.y), FRAME)
	var column := side * FRAMES_PER_FACING + posmod(frame, FRAMES_PER_FACING)
	return Rect2i(Vector2i(column * FRAME.x, ROW_WALK * FRAME.y), FRAME)


## A number per person and layer. Hashing the pair, rather than shifting one
## hash, keeps ids that differ only in their last characters from landing on
## the same style.
static func _roll(person_id: String, layer: String) -> int:
	return ("%s/%s" % [person_id, layer]).hash()


## Picks a style — the chosen one if the art has it, else one from the hash —
## then the variant of it closest in colour.
static func _styled(entries: Array, h: int, wanted: Color, chosen: String = "") -> String:
	if entries.is_empty():
		return ""
	var offered: Array[String] = []
	for entry: Dictionary in entries:
		var style := str(entry.get("style", ""))
		if not offered.has(style):
			offered.append(style)
	offered.sort()
	var style := chosen if offered.has(chosen) else offered[posmod(h, offered.size())]
	var variants: Array = entries.filter(func(e: Dictionary) -> bool: return str(e.get("style", "")) == style)
	return _closest(variants, wanted)


static func _closest(entries: Array, wanted: Color) -> String:
	var best := ""
	var best_distance := INF
	for entry: Dictionary in entries:
		var colour := Color(str(entry.get("colour", "#000000")))
		var distance := Vector3(colour.r - wanted.r, colour.g - wanted.g, colour.b - wanted.b).length_squared()
		if distance < best_distance:
			best_distance = distance
			best = str(entry["file"])
	return best


static func _palette_colour(palette: Dictionary, key: String) -> Color:
	var value: Variant = palette.get(key, CharacterFigure.DEFAULTS[key])
	if value is Color:
		return value
	return Color(str(value))
