class_name DataRegistry
extends RefCounted
## Loads authored content from res://data/*.json.
##
## Authored content is JSON rather than Godot .tres resources on purpose:
## JSON diffs cleanly in git, can be hand-edited or generated by tools, and
## needs no editor import step (so headless tests load the real data). See
## DECISIONS.md (D-004).
##
## Every table is validated on load. A malformed entry is dropped with a
## logged error rather than crashing, so one bad content file cannot make
## the game unbootable.

const DATA_DIR := "res://data/"

## table name -> required keys
const REQUIRED_KEYS := {
	"regions": ["id", "name_key"],
	"locations": ["id", "region", "name_key"],
	"occupations": ["id", "name_key"],
	"schedules": ["id", "blocks"],
	"npcs": ["id", "name", "home", "schedule"],
	"items": ["id", "name_key"],
	"skills": ["id", "name_key"],
	"backgrounds": ["id", "name_key"],
	"maps": ["id", "region", "width", "height", "spawn"],
	"interiors": ["id", "interior_of", "width", "height", "door"],
	"shops": ["id", "stock"],
	"jobs": ["id", "occupation", "workplace", "shift_start", "shift_end", "wage"],
	"quests": ["id", "name_key", "stages"],
	"errands": ["id", "name_key", "giver", "item", "count", "reward"],
	"asks": ["id", "npc", "skill", "grades"],
	"bins": ["id", "loot"],
	"recipes": ["id", "name_key", "inputs", "outputs"],
}

var tables: Dictionary = {}          # table -> { id -> entry }
var load_errors: Array[String] = []


## Loads every known table. Returns true when all loaded without errors.
func load_all() -> bool:
	tables.clear()
	load_errors.clear()
	for table_name in REQUIRED_KEYS:
		_load_table(table_name)
	if load_errors.is_empty():
		Log.info("data", "Content loaded", _counts())
	else:
		Log.error("data", "Content loaded with errors", {"errors": load_errors.size()})
	return load_errors.is_empty()


func table(name: String) -> Dictionary:
	return tables.get(name, {})


func get_entry(table_name: String, id: String) -> Dictionary:
	return table(table_name).get(id, {})


func has_entry(table_name: String, id: String) -> bool:
	return table(table_name).has(id)


func ids(table_name: String) -> Array:
	return table(table_name).keys()


## All entries in a table whose `field` equals `value`.
func find_by(table_name: String, field: String, value: Variant) -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	for id in table(table_name):
		var entry: Dictionary = table(table_name)[id]
		if entry.get(field) == value:
			out.append(entry)
	return out


## Cross-table integrity check, run after load_all(). Returns error strings.
## Catches the class of bug where an NPC points at a location that was renamed.
func validate_references() -> Array[String]:
	var problems: Array[String] = []
	for id in table("locations"):
		var loc: Dictionary = table("locations")[id]
		if not has_entry("regions", str(loc.get("region", ""))):
			problems.append("location '%s' references unknown region '%s'" % [id, loc.get("region")])
	for id in table("npcs"):
		var npc: Dictionary = table("npcs")[id]
		if not has_entry("locations", str(npc.get("home", ""))):
			problems.append("npc '%s' references unknown home '%s'" % [id, npc.get("home")])
		if not has_entry("schedules", str(npc.get("schedule", ""))):
			problems.append("npc '%s' references unknown schedule '%s'" % [id, npc.get("schedule")])
		var occ := str(npc.get("occupation", ""))
		if not occ.is_empty() and not has_entry("occupations", occ):
			problems.append("npc '%s' references unknown occupation '%s'" % [id, occ])
		var work := str(npc.get("workplace", ""))
		if not work.is_empty() and not has_entry("locations", work):
			problems.append("npc '%s' references unknown workplace '%s'" % [id, work])
		problems.append_array(_npc_nature_problems(id, npc))
	for id in table("schedules"):
		var sched: Dictionary = table("schedules")[id]
		for block in sched.get("blocks", []):
			var loc_id := str(block.get("location", ""))
			if loc_id.begins_with("@"):
				continue  # symbolic token, resolved per NPC at runtime
			if not loc_id.is_empty() and not has_entry("locations", loc_id):
				problems.append("schedule '%s' references unknown location '%s'" % [id, loc_id])
	for id in table("maps"):
		problems.append_array(_map_reference_problems(id, table("maps")[id]))
	for id in table("interiors"):
		problems.append_array(_interior_reference_problems(id, table("interiors")[id]))
	for id in table("shops"):
		problems.append_array(_shop_reference_problems(id, table("shops")[id]))
	for id in table("jobs"):
		problems.append_array(_job_reference_problems(id, table("jobs")[id]))
	for id in table("quests"):
		problems.append_array(_quest_reference_problems(id, table("quests")[id]))
	for id in table("asks"):
		problems.append_array(_ask_reference_problems(id, table("asks")[id]))
	for id in table("bins"):
		var loot: Variant = table("bins")[id].get("loot", [])
		if typeof(loot) != TYPE_ARRAY:
			problems.append("bin table '%s' loot must be a list" % id)
			continue
		for entry: Dictionary in loot:
			if not has_entry("items", str(entry.get("item", ""))):
				problems.append("bin table '%s' holds unknown item '%s'" % [id, entry.get("item")])
			if float(entry.get("weight", 0)) <= 0.0:
				problems.append("bin table '%s' gives '%s' no weight" % [id, entry.get("item")])
	problems.append_array(_recipe_problems())
	for id in table("errands"):
		var errand: Dictionary = table("errands")[id]
		if not has_entry("npcs", str(errand.get("giver", ""))):
			problems.append("errand '%s' references unknown giver '%s'" % [id, errand.get("giver")])
		if not has_entry("items", str(errand.get("item", ""))):
			problems.append("errand '%s' asks for unknown item '%s'" % [id, errand.get("item")])
	for id in table("backgrounds"):
		var occupation := str(table("backgrounds")[id].get("job", ""))
		if occupation != "" and find_by("jobs", "occupation", occupation).is_empty():
			problems.append("background '%s' gives occupation '%s', which no job offers" % [id, occupation])
	return problems


## An ask is put to someone who exists, turns on a skill that exists, waits on
## a quest that exists, and says what each of the four grades does, in effects
## the game knows (D-053).
func _ask_reference_problems(id: String, ask: Dictionary) -> Array[String]:
	var problems: Array[String] = []
	if not has_entry("npcs", str(ask.get("npc", ""))):
		problems.append("ask '%s' is put to unknown person '%s'" % [id, ask.get("npc")])
	if not has_entry("skills", str(ask.get("skill", ""))):
		problems.append("ask '%s' turns on unknown skill '%s'" % [id, ask.get("skill")])
	var requires: Dictionary = ask.get("requires", {})
	var quest := str(requires.get("quest", ""))
	if quest != "" and not has_entry("quests", quest):
		problems.append("ask '%s' waits on unknown quest '%s'" % [id, quest])
	## M8 step 11: an ask that requires dealing must be put to someone who
	## actually deals, or it could never be offered.
	if bool(requires.get("deals", false)) and (get_entry("npcs", str(ask.get("npc", ""))).get("deals", []) as Array).is_empty():
		problems.append("ask '%s' requires dealing but '%s' deals from nothing" % [id, ask.get("npc")])
	var grades: Dictionary = ask.get("grades", {})
	for grade in AskRules.GRADES:
		if not grades.has(grade):
			problems.append("ask '%s' does not say what '%s' does" % [id, grade])
			continue
		for effect: Dictionary in grades[grade]:
			if not AskDirector.EFFECTS.has(str(effect.get("do", ""))):
				problems.append("ask '%s' has an unknown effect '%s'" % [id, effect.get("do")])
			if effect.has("quest") and not has_entry("quests", str(effect["quest"])):
				problems.append("ask '%s' changes unknown quest '%s'" % [id, effect["quest"]])
	return problems


## A quest's giver, starting background and every person, place and job its
## stages wait on must exist, and every deed it counts must be one the game
## announces (D-044).
func _quest_reference_problems(id: String, quest: Dictionary) -> Array[String]:
	var problems: Array[String] = []
	var giver := str(quest.get("giver", ""))
	if giver != "" and not has_entry("npcs", giver):
		problems.append("quest '%s' references unknown giver '%s'" % [id, giver])
	var collection: Dictionary = quest.get("collection", {})
	if not collection.is_empty() and not has_entry("npcs", str(collection.get("holder", ""))):
		problems.append("quest '%s' is collected by unknown person '%s'" % [id, collection.get("holder")])
	var background := str((quest.get("starts", {}) as Dictionary).get("background", ""))
	if background != "" and not has_entry("backgrounds", background):
		problems.append("quest '%s' starts for unknown background '%s'" % [id, background])
	for stage in quest.get("stages", []):
		var when: Dictionary = (stage as Dictionary).get("when", {})
		var deed := str(when.get("deed", ""))
		if deed != "" and not QuestRules.DEEDS.has(deed):
			problems.append("quest '%s' waits on unknown deed '%s'" % [id, deed])
		var pattern: Dictionary = when.get("match", {})
		for field in pattern:
			var table_name: String = {"npc": "npcs", "job": "jobs", "location": "locations", "subject": "", "item": "items"}.get(field, "")
			var value := str(pattern[field])
			if field == "subject":
				table_name = "npcs" if value.begins_with("npc_") else "locations"
			if table_name != "" and not has_entry(table_name, value):
				problems.append("quest '%s' waits on unknown %s '%s'" % [id, field, value])
		var feeling: Dictionary = when.get("feeling", {})
		if not feeling.is_empty() and not has_entry("npcs", str(feeling.get("npc", ""))):
			problems.append("quest '%s' waits on how unknown '%s' feels" % [id, feeling.get("npc")])
	return problems


## A job is an occupation at a place that exists, for an employer who exists
## (or nobody, for casual work), teaching skills that exist (D-042).
func _job_reference_problems(id: String, job: Dictionary) -> Array[String]:
	var problems: Array[String] = []
	if not has_entry("occupations", str(job.get("occupation", ""))):
		problems.append("job '%s' references unknown occupation '%s'" % [id, job.get("occupation")])
	if not has_entry("locations", str(job.get("workplace", ""))):
		problems.append("job '%s' references unknown workplace '%s'" % [id, job.get("workplace")])
	var employer := str(job.get("employer", ""))
	if employer != "" and not has_entry("npcs", employer):
		problems.append("job '%s' references unknown employer '%s'" % [id, employer])
	for skill_id in job.get("skills", []):
		if not has_entry("skills", str(skill_id)):
			problems.append("job '%s' teaches unknown skill '%s'" % [id, skill_id])
	if int(job.get("shift_end", 0)) <= int(job.get("shift_start", 0)):
		problems.append("job '%s' ends before it starts" % id)
	return problems


## An NPC's nature, if authored, names only the four known axes and keeps
## each one in [0, 1]; anything they deal from is a shop that exists (M8
## D-082 — the schema is frozen here, deal ids are authored alongside the
## shops that give them meaning in a later step).
func _npc_nature_problems(id: String, npc: Dictionary) -> Array[String]:
	var problems: Array[String] = []
	var raw_nature: Variant = npc.get("nature", {})
	if raw_nature is Dictionary:
		var nature: Dictionary = raw_nature
		for axis in nature:
			if not Npc.NATURE_AXES.has(str(axis)):
				problems.append("npc '%s' has an unknown nature axis '%s'" % [id, axis])
				continue
			var value: Variant = nature[axis]
			if typeof(value) != TYPE_FLOAT and typeof(value) != TYPE_INT:
				problems.append("npc '%s' nature axis '%s' is not a number" % [id, axis])
			elif float(value) < 0.0 or float(value) > 1.0:
				problems.append("npc '%s' nature axis '%s' is out of range [0, 1]" % [id, axis])
	else:
		problems.append("npc '%s' nature must be an object of axis -> number" % id)
	for deal in npc.get("deals", []):
		if not has_entry("shops", str(deal)):
			problems.append("npc '%s' deals from unknown shop '%s'" % [id, deal])
	return problems


## A shop is a place a player can walk up to (`location`) or a person they
## deal with wherever found (`keeper`, an npc id) — exactly one, never both
## and never neither. A kept shop's keeper must name it back in their own
## `deals`, so a shop and a dealer always agree who deals what (M8 D-084).
## Selling things that exist, buying kinds of thing that exist (D-039).
func _shop_reference_problems(id: String, shop: Dictionary) -> Array[String]:
	var problems: Array[String] = []
	var location := str(shop.get("location", ""))
	var keeper := str(shop.get("keeper", ""))
	if location.is_empty() == keeper.is_empty():
		problems.append("shop '%s' must have exactly one of location or keeper" % id)
	elif not location.is_empty():
		if not has_entry("locations", location):
			problems.append("shop '%s' references unknown location '%s'" % [id, location])
	elif not keeper.is_empty():
		if not has_entry("npcs", keeper):
			problems.append("shop '%s' is kept by unknown person '%s'" % [id, keeper])
		else:
			var deals: Array = get_entry("npcs", keeper).get("deals", [])
			if not deals.has(id):
				problems.append("shop '%s' is kept by '%s', whose deals do not name it" % [id, keeper])
	var legality := str(shop.get("legality", "legal"))
	if not ["legal", "grey", "illicit"].has(legality):
		problems.append("shop '%s' has an unknown legality '%s'" % [id, legality])
	var requires: Dictionary = shop.get("requires", {})
	var required_quest := str(requires.get("quest", ""))
	if not required_quest.is_empty() and not has_entry("quests", required_quest):
		problems.append("shop '%s' requires unknown quest '%s'" % [id, required_quest])
	var stock: Variant = shop.get("stock", {})
	if typeof(stock) != TYPE_DICTIONARY:
		return problems + ["shop '%s' stock must be an object of item -> count" % id]
	for item_id in stock:
		if not has_entry("items", str(item_id)):
			problems.append("shop '%s' sells unknown item '%s'" % [id, item_id])
	var kinds: Array = []
	for item_id in table("items"):
		kinds.append(str(table("items")[item_id].get("kind", "")))
	for kind in shop.get("buys", []):
		if not kinds.has(str(kind)):
			problems.append("shop '%s' buys unknown kind '%s'" % [id, kind])
	return problems


## Recipes (D-070): every item exists, what is kept was put in, and no two
## recipes take the same things, because the grid could not tell them apart.
func _recipe_problems() -> Array[String]:
	var problems: Array[String] = []
	var seen := {}
	for id in table("recipes"):
		var recipe: Dictionary = table("recipes")[id]
		for side in ["inputs", "outputs"]:
			var things: Variant = recipe.get(side, {})
			if typeof(things) != TYPE_DICTIONARY or (things as Dictionary).is_empty():
				problems.append("recipe '%s' has no %s" % [id, side])
				continue
			for item_id in things:
				if not has_entry("items", str(item_id)):
					problems.append("recipe '%s' %s unknown item '%s'" % [id, "uses" if side == "inputs" else "makes", item_id])
				elif int(things[item_id]) < 1:
					problems.append("recipe '%s' has a count below one for '%s'" % [id, item_id])
		for kept in recipe.get("keeps", []):
			if not (recipe.get("inputs", {}) as Dictionary).has(str(kept)):
				problems.append("recipe '%s' keeps '%s', which it does not use" % [id, kept])
		var lays: Array[Dictionary] = []   # every way of laying the grid that would make it
		if bool(recipe.get("fire", false)):
			for source in CraftRules.FIRE:
				var with_light := CraftRules.inputs_of(recipe)
				with_light[source] = int(with_light.get(source, 0)) + 1
				lays.append(with_light)
		else:
			lays.append(CraftRules.inputs_of(recipe))
		for lay in lays:
			var key := JSON.stringify(lay, "", true)
			if seen.has(key) and seen[key] != id:
				problems.append("recipes '%s' and '%s' take the same things" % [seen[key], id])
			seen[key] = id
	return problems


## An interior is the inside of a building that stands on its region's map.
func _interior_reference_problems(id: String, interior: Dictionary) -> Array[String]:
	var problems: Array[String] = []
	var loc_id := str(interior.get("interior_of", ""))
	if not has_entry("locations", loc_id):
		return ["interior '%s' belongs to unknown location '%s'" % [id, loc_id]]
	var region := str(get_entry("locations", loc_id).get("region", ""))
	var standing := false
	for map_id in table("maps"):
		var map: Dictionary = table("maps")[map_id]
		if str(map.get("region", "")) != region:
			continue
		for building in map.get("buildings", []):
			if str(building.get("location", "")) == loc_id:
				standing = true
	if not standing:
		problems.append("interior '%s' belongs to '%s', which is not a building on a map" % [id, loc_id])
	return problems


## A map may only place locations of its own region, and may only lead to
## regions that exist. Layout geometry is checked by DistrictMap itself.
func _map_reference_problems(id: String, map: Dictionary) -> Array[String]:
	var problems: Array[String] = []
	var region := str(map.get("region", ""))
	if not has_entry("regions", region):
		problems.append("map '%s' references unknown region '%s'" % [id, region])
	var entries: Array = []
	entries.append_array(map.get("buildings", []))
	entries.append_array(map.get("places", []))
	for entry in entries:
		var loc_id := str(entry.get("location", ""))
		if not has_entry("locations", loc_id):
			problems.append("map '%s' places unknown location '%s'" % [id, loc_id])
		elif str(get_entry("locations", loc_id).get("region", "")) != region:
			problems.append("map '%s' places '%s', which belongs to another region" % [id, loc_id])
	for way_out in map.get("exits", []):
		if not has_entry("regions", str(way_out.get("to", ""))):
			problems.append("map '%s' exits to unknown region '%s'" % [id, way_out.get("to")])
	return problems


func _load_table(table_name: String) -> void:
	var path := DATA_DIR + table_name + ".json"
	tables[table_name] = {}
	if not FileAccess.file_exists(path):
		load_errors.append("missing data file: " + path)
		return
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		load_errors.append("cannot open: " + path)
		return
	var text := file.get_as_text()
	file.close()

	var parsed: Variant = SafeJson.parse(text)
	if typeof(parsed) != TYPE_ARRAY:
		load_errors.append("%s must contain a JSON array" % path)
		return

	var required: Array = REQUIRED_KEYS[table_name]
	var bucket: Dictionary = {}
	for raw in parsed:
		if typeof(raw) != TYPE_DICTIONARY:
			load_errors.append("%s: entry is not an object" % table_name)
			continue
		var entry: Dictionary = raw
		var missing: Array[String] = []
		for key in required:
			if not entry.has(key):
				missing.append(str(key))
		if not missing.is_empty():
			load_errors.append("%s: entry %s missing %s" % [
				table_name, entry.get("id", "<no id>"), ", ".join(missing)])
			continue
		var id := str(entry["id"])
		if bucket.has(id):
			load_errors.append("%s: duplicate id '%s'" % [table_name, id])
			continue
		bucket[id] = entry
	tables[table_name] = bucket


func _counts() -> Dictionary:
	var out := {}
	for name in tables:
		out[name] = tables[name].size()
	return out
