class_name DataRegistry
extends RefCounted
## Loads authored content from res://data/*.json.
##
## Authored content is JSON rather than Godot .tres resources on purpose:
## JSON diffs cleanly in git, can be hand-edited or generated by tools, and
## needs no editor import step (so headless tests load the real data). See
## DECISIONS.md (D-004).
##
## Every table is validated on load. A malformed entry is dropped with a
## logged error rather than crashing, so one bad content file cannot make
## the game unbootable.

const DATA_DIR := "res://data/"

## table name -> required keys
const REQUIRED_KEYS := {
	"regions": ["id", "name_key"],
	"locations": ["id", "region", "name_key"],
	"occupations": ["id", "name_key"],
	"schedules": ["id", "blocks"],
	"npcs": ["id", "name", "home", "schedule"],
	"items": ["id", "name_key"],
	"skills": ["id", "name_key"],
	"backgrounds": ["id", "name_key"],
	"maps": ["id", "region", "width", "height", "spawn"],
	"interiors": ["id", "interior_of", "width", "height", "door"],
}

var tables: Dictionary = {}          # table -> { id -> entry }
var load_errors: Array[String] = []


## Loads every known table. Returns true when all loaded without errors.
func load_all() -> bool:
	tables.clear()
	load_errors.clear()
	for table_name in REQUIRED_KEYS:
		_load_table(table_name)
	if load_errors.is_empty():
		Log.info("data", "Content loaded", _counts())
	else:
		Log.error("data", "Content loaded with errors", {"errors": load_errors.size()})
	return load_errors.is_empty()


func table(name: String) -> Dictionary:
	return tables.get(name, {})


func get_entry(table_name: String, id: String) -> Dictionary:
	return table(table_name).get(id, {})


func has_entry(table_name: String, id: String) -> bool:
	return table(table_name).has(id)


func ids(table_name: String) -> Array:
	return table(table_name).keys()


## All entries in a table whose `field` equals `value`.
func find_by(table_name: String, field: String, value: Variant) -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	for id in table(table_name):
		var entry: Dictionary = table(table_name)[id]
		if entry.get(field) == value:
			out.append(entry)
	return out


## Cross-table integrity check, run after load_all(). Returns error strings.
## Catches the class of bug where an NPC points at a location that was renamed.
func validate_references() -> Array[String]:
	var problems: Array[String] = []
	for id in table("locations"):
		var loc: Dictionary = table("locations")[id]
		if not has_entry("regions", str(loc.get("region", ""))):
			problems.append("location '%s' references unknown region '%s'" % [id, loc.get("region")])
	for id in table("npcs"):
		var npc: Dictionary = table("npcs")[id]
		if not has_entry("locations", str(npc.get("home", ""))):
			problems.append("npc '%s' references unknown home '%s'" % [id, npc.get("home")])
		if not has_entry("schedules", str(npc.get("schedule", ""))):
			problems.append("npc '%s' references unknown schedule '%s'" % [id, npc.get("schedule")])
		var occ := str(npc.get("occupation", ""))
		if not occ.is_empty() and not has_entry("occupations", occ):
			problems.append("npc '%s' references unknown occupation '%s'" % [id, occ])
		var work := str(npc.get("workplace", ""))
		if not work.is_empty() and not has_entry("locations", work):
			problems.append("npc '%s' references unknown workplace '%s'" % [id, work])
	for id in table("schedules"):
		var sched: Dictionary = table("schedules")[id]
		for block in sched.get("blocks", []):
			var loc_id := str(block.get("location", ""))
			if loc_id.begins_with("@"):
				continue  # symbolic token, resolved per NPC at runtime
			if not loc_id.is_empty() and not has_entry("locations", loc_id):
				problems.append("schedule '%s' references unknown location '%s'" % [id, loc_id])
	for id in table("maps"):
		problems.append_array(_map_reference_problems(id, table("maps")[id]))
	for id in table("interiors"):
		problems.append_array(_interior_reference_problems(id, table("interiors")[id]))
	return problems


## An interior is the inside of a building that stands on its region's map.
func _interior_reference_problems(id: String, interior: Dictionary) -> Array[String]:
	var problems: Array[String] = []
	var loc_id := str(interior.get("interior_of", ""))
	if not has_entry("locations", loc_id):
		return ["interior '%s' belongs to unknown location '%s'" % [id, loc_id]]
	var region := str(get_entry("locations", loc_id).get("region", ""))
	var standing := false
	for map_id in table("maps"):
		var map: Dictionary = table("maps")[map_id]
		if str(map.get("region", "")) != region:
			continue
		for building in map.get("buildings", []):
			if str(building.get("location", "")) == loc_id:
				standing = true
	if not standing:
		problems.append("interior '%s' belongs to '%s', which is not a building on a map" % [id, loc_id])
	return problems


## A map may only place locations of its own region, and may only lead to
## regions that exist. Layout geometry is checked by DistrictMap itself.
func _map_reference_problems(id: String, map: Dictionary) -> Array[String]:
	var problems: Array[String] = []
	var region := str(map.get("region", ""))
	if not has_entry("regions", region):
		problems.append("map '%s' references unknown region '%s'" % [id, region])
	var entries: Array = []
	entries.append_array(map.get("buildings", []))
	entries.append_array(map.get("places", []))
	for entry in entries:
		var loc_id := str(entry.get("location", ""))
		if not has_entry("locations", loc_id):
			problems.append("map '%s' places unknown location '%s'" % [id, loc_id])
		elif str(get_entry("locations", loc_id).get("region", "")) != region:
			problems.append("map '%s' places '%s', which belongs to another region" % [id, loc_id])
	for way_out in map.get("exits", []):
		if not has_entry("regions", str(way_out.get("to", ""))):
			problems.append("map '%s' exits to unknown region '%s'" % [id, way_out.get("to")])
	return problems


func _load_table(table_name: String) -> void:
	var path := DATA_DIR + table_name + ".json"
	tables[table_name] = {}
	if not FileAccess.file_exists(path):
		load_errors.append("missing data file: " + path)
		return
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		load_errors.append("cannot open: " + path)
		return
	var text := file.get_as_text()
	file.close()

	var parsed: Variant = SafeJson.parse(text)
	if typeof(parsed) != TYPE_ARRAY:
		load_errors.append("%s must contain a JSON array" % path)
		return

	var required: Array = REQUIRED_KEYS[table_name]
	var bucket: Dictionary = {}
	for raw in parsed:
		if typeof(raw) != TYPE_DICTIONARY:
			load_errors.append("%s: entry is not an object" % table_name)
			continue
		var entry: Dictionary = raw
		var missing: Array[String] = []
		for key in required:
			if not entry.has(key):
				missing.append(str(key))
		if not missing.is_empty():
			load_errors.append("%s: entry %s missing %s" % [
				table_name, entry.get("id", "<no id>"), ", ".join(missing)])
			continue
		var id := str(entry["id"])
		if bucket.has(id):
			load_errors.append("%s: duplicate id '%s'" % [table_name, id])
			continue
		bucket[id] = entry
	tables[table_name] = bucket


func _counts() -> Dictionary:
	var out := {}
	for name in tables:
		out[name] = tables[name].size()
	return out
